spring:
  application:
    name: zuul-proxy

server:
  port: 8303

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    mongo-db-service:
      path: /db-service/**
      url: http://localhost:8300
    stock-service:
      path: /stock-service/**
      url: http://localhost:8301
